### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [youknowone/gitstat#2]
I'd like to know how you intended this tool to be used and shared. http://choosealicense.com/ might help. Also, GitHub has a convenient feature where you can get many licenses by clicking "new file" in the GitHub UI, naming it license, and picking the template you want from the dropdown which appears at the right. 

Thank you for building Gitstat; it's an incredibly helpful little tool!

**Comment by youknowone** [comment]
Thanks to notify it. I didn't know I missed license file here.
It is 2-clause BSD so free to use everywhere and anyway.
